### ISSUE TITLE
`go:generate sumgen` comment added to `go doc` output

### ISSUE THREAD

**Issue by mewmew** [smasher164/sumgen#1]
First off, cool and really quite useful tool! Especially when writing AST packages that are so heavy on the use of sumtypes.

Getting up and running was really easy, but I did stumble on a small issue where `sumgen` only generates the `foo_sumgen.go` file when invoking `go generate` if the `//go:generate sumgen ...` comment is attached to the doc comment of the corresponding Go interface definition.

In other words, generating `foo_sumgen.go` works for:

```go
//go:generate sumgen Type = *Typedef | *VoidType | *IntType | *FloatType | *ArrayType | *EnumType | *FuncType | *PointerType | *StructType | *UnionType
// Type is a C type.
type Type interface {
	// String returns the C syntax representation use of the type.
	fmt.Stringer
	// CString returns the C syntax representation definition of the type.
	CStringer
	// Equal reports whether t and u are of equal type.
	Equal(u Type) bool
}
```

However, it does not work for the following (notice that there is a newline in between the `//go:generate sumgen ...` comment and the doc comment of `Type`):

```go
//go:generate sumgen Type = *Typedef | *VoidType | *IntType | *FloatType | *ArrayType | *EnumType | *FuncType | *PointerType | *StructType | *UnionType

// Type is a C type.
type Type interface {
	// String returns the C syntax representation use of the type.
	fmt.Stringer
	// CString returns the C syntax representation definition of the type.
	CStringer
	// Equal reports whether t and u are of equal type.
	Equal(u Type) bool
}
```

One issue with this is that the generated documentation by `go doc` now includes the `go:generate comment`.

![screenshot_2019-12-12_09:05:57](https://user-images.githubusercontent.com/1414531/70693911-b092dc00-1cbe-11ea-9d9b-768e1451b89d.png)

Other than that, the tool works as expected :)

Cheers,
Robin

**Comment by smasher164** [comment]
Thanks for using this tool! I agree that the position of the `//go:generate` comment shouldn't affect the type for which sumgen generates methods.

It is probably best to refactor this tool to accept command line flags, instead of parsing the sum-type declaration through the comment, which I originally did because of a misunderstanding of how `go generate` worked. I can also take advantage of https://godoc.org/golang.org/x/tools/go/packages to parse and type-check the entire package.

This way, the comment isn't actually required, and the tool can be run standalone. Additionally, it can be placed anywhere in the file. I'll take a look at this on Wednesday (12/18) after my final exams.

**Comment by mewmew** [comment]
> It is probably best to refactor this tool to accept command line flags, instead of parsing the sum-type declaration through the comment, which I originally did because of a misunderstanding of how go generate worked. I can also take advantage of https://godoc.org/golang.org/x/tools/go/packages to parse and type-check the entire package.

Sounds good! If you want inspiration, [stringer](https://github.com/golang/tools/tree/master/cmd/stringer) does something similar and may be used both from command-line and in `go:generate` comments.

> This way, the comment isn't actually required, and the tool can be run standalone. Additionally, it can be placed anywhere in the file. I'll take a look at this on Wednesday (12/18) after my final exams.

Haha, perfect! I just had my final assignment today :) Now it's winter break! With both time for skiing, ice skating and of course coding.

Wish you good luck on the exams and a happy start of the winter break.

**Comment by smasher164** [comment]
Based on the way stringer does it, running `sumgen` in the current directory should process the package corresponding to the current directory. The arguments would be the same as they are now, except that when they are passed on the command line, the `|` operator needs to be escaped. It would be better for users to run it in quotes like this:
```
$ sumgen "Type = *A | B"
```

**Comment by mewmew** [comment]
> It would be better for users to run it in quotes like this:

Yeah, using quotes makes sense.

**Comment by smasher164** [comment]
Please try the latest version of the tool and LMK how it works for you. Thanks!

**Comment by mewmew** [comment]
Hi @smasher164!

Thanks, I updated to the latest version. And it works well.

However, there seem to be a small typo in the `sumgen` usage documentation.

```
$ sumgen -h
usage: sumgen "InterfaceName = TypeNameA, *TypeNameB, ..."
```

The `sumgen` usage documentation suggests that `,` (comma) is used as separator.

But using `,` results in the following error:

```go
//go:generate sumgen "Type = *Typedef, *VoidType, *IntType, *FloatType, *ArrayType, *EnumType, *FuncType, *PointerType, *StructType, *UnionType"
```

```
$ go generate
sumgen: declaration must satisfy the form
	Def = LhsType "=" RhsType { "|" RhsType } .
	LhsType = identifier .
	RhsType = [ * ] identifier .
```

As such, I changed the `sumgen` command to use `|` (pipe) as separating character, and then it worked perfectly.

```go
//go:generate sumgen "Type = *Typedef | *VoidType | *IntType | *FloatType | *ArrayType | *EnumType | *FuncType | *PointerType | *StructType | *UnionType"
```

So, a small update to the usage docs and then you are good to go!

Have a happy winter holidays.

Cheers,
Robin

**Comment by smasher164** [comment]
@mewmew Thanks for catching that! Fixed.

Happy Holidays to you as well! :)
Akhil
